'use strict';
// ═══════════════════════════════════════════════════════════════════════════════
//  AllMight — Execution Sandbox  v1.0
// ───────────────────────────────────────────────────────────────────────────────
//  PLACEMENT : scripts/execution/execution_sandbox.js
//  STATUS    : NEW — Boss ruling 2026-04-15
//
//  Time-based replay engine. No RPC. No Redis. No live execution.
//
//  Input:
//    blueprints.jsonl   — trade blueprints from the session
//    price_replay.jsonl — venue-side snapshots generated by generate_price_replay.js
//
//  Logic per blueprint:
//    entry price  = nearest replay row at or before blueprint.ts for entry venue
//    exit price   = nearest replay row at or after ts + delayMs for exit venue
//    spread       = recomputed from real replay prices
//    PnL          = computePnL() from pnl_engine.js
//    class        = classifyExecution()
//
//  If no replay row found within tolerance: outcome = SANDBOX_NO_FILL
// ═══════════════════════════════════════════════════════════════════════════════

const fs       = require('fs');
const readline = require('readline');
const { computePnL, classifyExecution } = require('./pnl_engine');

// ─── TIMING CONSTANTS ─────────────────────────────────────────────────────────

// Tolerance window beyond target exit time before declaring no-fill
// Boss brief: 0ms→1s tolerance, 500ms→2s, 1000ms→3s
function delayToleranceMs(delayMs) {
  if (delayMs <= 0)   return 1000;
  if (delayMs <= 500) return 2000;
  return 3000;
}

// ─── FILE I/O ─────────────────────────────────────────────────────────────────

async function readJsonl(filePath) {
  const rows = [];
  const rl = readline.createInterface({
    input: fs.createReadStream(filePath, { encoding: 'utf8' }),
    crlfDelay: Infinity,
  });
  for await (const line of rl) {
    if (!line.trim()) continue;
    try { rows.push(JSON.parse(line)); } catch {}
  }
  return rows;
}

// ─── REPLAY INDEX ─────────────────────────────────────────────────────────────

function toMillis(ts) {
  const ms = Date.parse(ts);
  return Number.isFinite(ms) ? ms : NaN;
}

/**
 * Build a lookup map keyed by "pair::venue" → sorted array of replay rows.
 * Sorting by ts ascending allows binary-search style lookups.
 */
function buildReplayIndex(rows) {
  const index = new Map();
  for (const row of rows) {
    if (!row?.pair || !row?.venue || !row?.ts) continue;
    const key = `${row.pair}::${row.venue}`;
    if (!index.has(key)) index.set(key, []);
    index.get(key).push(row);
  }
  for (const arr of index.values()) {
    arr.sort((a, b) => toMillis(a.ts) - toMillis(b.ts));
  }
  return index;
}

// ─── REPLAY LOOKUP ────────────────────────────────────────────────────────────

function findNearestAtOrBefore(rows, targetMs) {
  let best = null;
  for (const row of rows) {
    const ms = toMillis(row.ts);
    if (!Number.isFinite(ms)) continue;
    if (ms <= targetMs) best = row;
    else break;
  }
  return best;
}

function findNearestAtOrAfter(rows, targetMs, maxDeltaMs) {
  for (const row of rows) {
    const ms = toMillis(row.ts);
    if (!Number.isFinite(ms)) continue;
    if (ms >= targetMs && ms <= targetMs + maxDeltaMs) return row;
  }
  return null;
}

// ─── SPREAD RECOMPUTATION ─────────────────────────────────────────────────────

/**
 * Recompute spread bps from actual replay prices.
 * Direction: BUY entry venue, SELL exit venue.
 * Positive spread = exit price > entry price (profit before fees).
 */
function recomputeSpreadBps(entryPrice, exitPrice) {
  if (!Number.isFinite(entryPrice) || !Number.isFinite(exitPrice) || entryPrice <= 0)
    return NaN;
  return ((exitPrice - entryPrice) / entryPrice) * 10000;
}

/**
 * Extract total feeBps for entry + exit.
 * Uses replay row feeBps if available, falls back to blueprint venue feePct.
 */
function extractFeeBps(bp, entryRow, exitRow) {
  // Replay rows carry feeBps from the venue's pool
  const entryFee = Number.isFinite(entryRow?.feeBps) ? entryRow.feeBps : null;
  const exitFee  = Number.isFinite(exitRow?.feeBps)  ? exitRow.feeBps  : null;
  if (entryFee !== null || exitFee !== null) {
    return (entryFee ?? 0) + (exitFee ?? 0);
  }
  // Fallback: blueprint venue feePct → convert to bps
  const entryFrac = bp?.venues?.entry?.feePct ?? 0;
  const exitFrac  = bp?.venues?.exit?.feePct  ?? 0;
  return (entryFrac + exitFrac) * 10000;
}

// ─── SINGLE BLUEPRINT SIMULATION ─────────────────────────────────────────────

function simulateOne({ bp, replayIndex, delayMs }) {
  const id         = bp?.blueprintId ?? null;
  const ts         = bp?.ts ?? null;
  const pair       = bp?.pair ?? null;
  const entryVenue = bp?.venues?.entry?.venue ?? null;
  const exitVenue  = bp?.venues?.exit?.venue  ?? null;
  const sizeUsd    = bp?.sizing?.targetUsd ?? bp?._context?.targetExecutionSizeUsd ?? 200;

  if (!id || !ts || !pair || !entryVenue || !exitVenue) {
    return {
      blueprintId: id, delayMs,
      outcome: 'SANDBOX_INVALID_BLUEPRINT',
      executionClass: 'EXECUTION_FAIL',
      reason: `missing fields: ${[!id&&'blueprintId',!ts&&'ts',!pair&&'pair',!entryVenue&&'entryVenue',!exitVenue&&'exitVenue'].filter(Boolean).join(',')}`,
    };
  }

  const entryRows = replayIndex.get(`${pair}::${entryVenue}`) || [];
  const exitRows  = replayIndex.get(`${pair}::${exitVenue}`)  || [];
  const t0        = toMillis(ts);
  const tol       = delayToleranceMs(delayMs);
  const entryRow  = findNearestAtOrBefore(entryRows, t0);
  const exitRow   = findNearestAtOrAfter(exitRows, t0 + delayMs, tol);

  if (!entryRow) {
    return { blueprintId: id, delayMs, outcome: 'SANDBOX_NO_FILL',
             executionClass: 'EXECUTION_FAIL', reason: `no entry replay row for ${pair}::${entryVenue} at ${ts}` };
  }
  if (!exitRow) {
    return { blueprintId: id, delayMs, outcome: 'SANDBOX_NO_FILL',
             executionClass: 'EXECUTION_FAIL', reason: `no exit replay row for ${pair}::${exitVenue} after ${ts}+${delayMs}ms` };
  }

  const spreadBps = recomputeSpreadBps(entryRow.price, exitRow.price);
  if (!Number.isFinite(spreadBps)) {
    return { blueprintId: id, delayMs, outcome: 'SANDBOX_BAD_SPREAD',
             executionClass: 'EXECUTION_FAIL', reason: 'spread recomputation failed' };
  }

  const feeBps = extractFeeBps(bp, entryRow, exitRow);
  const gasUsd = bp?.economics?.gasCostUsd ?? 0.02;
  const pnl    = computePnL({ spreadBps, feeBps, sizeUsd, gasUsd });

  // worstNetUsd = net at current replay spread (no additional stress — replay IS the reality)
  const executionClass = classifyExecution({
    realNetUsd  : pnl.netProfitUsd,
    worstNetUsd : pnl.netProfitUsd,
  });

  const outcome = pnl.wouldRevert ? 'SANDBOX_LOSS'
                : executionClass === 'EXECUTION_VIABLE' ? 'SANDBOX_PROFIT'
                : 'SANDBOX_BREAKEVEN';

  return {
    blueprintId    : id,
    pair,
    profile        : bp?._context?.activeProfile ?? null,
    regime         : bp?._context?.regime ?? null,
    heatClass      : bp?._context?.heatClass ?? null,
    delayMs,
    entryTime      : entryRow.ts,
    exitTime       : exitRow.ts,
    entryVenue,
    exitVenue,
    entryPrice     : entryRow.price,
    exitPrice      : exitRow.price,
    spreadBps      : +spreadBps.toFixed(4),
    feeBps,
    sizeUsd,
    expectedPnL    : bp?.economics?.netProfitUsd ?? null,
    realPnL        : pnl.netProfitUsd,
    grossProfitUsd : pnl.grossProfitUsd,
    feeCostUsd     : pnl.feeCostUsd,
    aaveFeeUsd     : pnl.aaveFeeUsd,
    gasUsd         : pnl.gasUsd,
    netEdgeBps     : pnl.netEdgeBps,
    wouldRevert    : pnl.wouldRevert,
    executionClass,
    outcome,
  };
}

// ─── BATCH RUNNER ─────────────────────────────────────────────────────────────

async function runSandbox({ blueprintsPath, replayPath, delaysMs = [0, 500, 1000] }) {
  const blueprints  = await readJsonl(blueprintsPath);
  const replayRows  = await readJsonl(replayPath);
  const replayIndex = buildReplayIndex(replayRows);
  const out = [];
  for (const bp of blueprints) {
    for (const delayMs of delaysMs) {
      out.push(simulateOne({ bp, replayIndex, delayMs }));
    }
  }
  return out;
}

module.exports = { readJsonl, buildReplayIndex, simulateOne, runSandbox };
