'use strict';

// Token registry loader + lookup.
// Source of truth: config/tokens/<chain>.json
// Generated by: scripts/tools/build_token_registry_from_pools.js
//
// Supported shapes:
// 1) Canonical:
//    { "chain":"ethereum","generatedAt":"...","tokens":{ "0x..":{symbol,decimals,address} } }
// 2) Legacy symbol-keyed:
//    { "WETH":{address:"0x..",symbol:"WETH",decimals:18}, ... }

const fs = require('fs');
const path = require('path');

const _cache = new Map();

function _normAddr(addr) {
  return String(addr || '').toLowerCase();
}

function _isAddressLike(value) {
  return /^0x[a-fA-F0-9]{40}$/.test(String(value || ''));
}

function _tokensPath(chain) {
  return path.resolve(process.cwd(), 'config', 'tokens', `${String(chain || '').toLowerCase()}.json`);
}

function loadRegistry(chain) {
  const key = String(chain || '').toLowerCase();
  if (_cache.has(key)) return _cache.get(key);

  const p = _tokensPath(key);
  if (!fs.existsSync(p)) {
    const empty = { chain: key, generatedAt: null, tokens: {} };
    _cache.set(key, empty);
    return empty;
  }

  const raw = fs.readFileSync(p, 'utf8');
  const obj = JSON.parse(raw);

  let sourceTokens;
  let generatedAt = null;

  if (obj && typeof obj === 'object' && obj.tokens && typeof obj.tokens === 'object') {
    generatedAt = obj.generatedAt || null;
    sourceTokens = obj.tokens;
  } else {
    sourceTokens = obj || {};
  }

  const normTokens = {};

  for (const [outerKey, meta] of Object.entries(sourceTokens)) {
    if (!meta || typeof meta !== 'object') continue;

    // Prefer actual address from meta.address; otherwise use outer key if it is address-like
    const addr = _isAddressLike(meta.address)
      ? meta.address
      : (_isAddressLike(outerKey) ? outerKey : null);

    if (!addr) continue;

    normTokens[_normAddr(addr)] = {
      address: meta.address || addr,
      symbol: meta.symbol || null,
      decimals: (meta.decimals === 0 || meta.decimals != null) ? Number(meta.decimals) : null,
      name: meta.name || null,
    };
  }

  const normalized = { chain: key, generatedAt, tokens: normTokens };
  _cache.set(key, normalized);
  return normalized;
}

function getToken(chain, address) {
  const reg = loadRegistry(chain);
  return reg.tokens[_normAddr(address)] || null;
}

function clearRegistryCache() {
  _cache.clear();
}

module.exports = {
  loadRegistry,
  getToken,
  clearRegistryCache,
};
