'use strict';

// Token registry loader + lookup.
// Source of truth: config/tokens/<chain>.json
// Generated by: scripts/tools/build_token_registry_from_pools.js
//
// Design goals:
// - Avoid RPC calls for ERC20 metadata (symbol/decimals) during hot-path fetchers
// - Keep fetchers deterministic and less dependent on flaky RPC nodes

const fs = require('fs');
const path = require('path');

const _cache = new Map();

function _normAddr(addr) {
  return (addr || '').toLowerCase();
}

function _tokensPath(chain) {
  return path.resolve(process.cwd(), 'config', 'tokens', `${chain}.json`);
}

function loadRegistry(chain) {
  const key = (chain || '').toLowerCase();
  if (_cache.has(key)) return _cache.get(key);

  const p = _tokensPath(key);
  if (!fs.existsSync(p)) {
    const empty = { chain: key, generatedAt: null, tokens: {} };
    _cache.set(key, empty);
    return empty;
  }

  const raw = fs.readFileSync(p, 'utf8');
  const obj = JSON.parse(raw);

  // Support two shapes:
  // 1) { "chain":"ethereum","generatedAt":"...","tokens":{ "0x..":{symbol,decimals,address} } }
  // 2) { "0x..":{symbol,decimals,address}, ... }  (legacy)
  let normalized;
  if (obj && typeof obj === 'object' && obj.tokens && typeof obj.tokens === 'object') {
    normalized = { chain: key, generatedAt: obj.generatedAt || null, tokens: obj.tokens };
  } else {
    normalized = { chain: key, generatedAt: null, tokens: obj || {} };
  }

  // Normalize keys
  const normTokens = {};
  for (const [addr, meta] of Object.entries(normalized.tokens)) {
    normTokens[_normAddr(addr)] = {
      address: meta.address || addr,
      symbol: meta.symbol || null,
      decimals: (meta.decimals === 0 || meta.decimals) ? Number(meta.decimals) : null,
      name: meta.name || null,
    };
  }
  normalized.tokens = normTokens;

  _cache.set(key, normalized);
  return normalized;
}

function getToken(chain, address) {
  const reg = loadRegistry(chain);
  const meta = reg.tokens[_normAddr(address)];
  return meta || null;
}

module.exports = {
  loadRegistry,
  getToken,
};
